### ISSUE TITLE
Update Planet4 Styleguide with introduction

### ISSUE THREAD

**Issue by LauraHilliger** [greenpeace/planet4#74] opened 2020-07-23 15:18 UTC
#Where did you find the bug?
https://planet4.greenpeace.org/styleguide/index.html

#What went wrong?
On the start and Introduction, the "homepage.md" isn't being displayed. I wanted to edit it a bit, and add some signposting to our [Design contribute section in the handbook](https://planet4.greenpeace.org/create/contribute/#design), and maybe spruce up the landing with the friendly images @WillMorrisJulien has been working on in [an onboarding document](https://docs.google.com/presentation/d/1WQGrLp7KcY2Vg5A6_jFv1pCipAMUmlXBKiAeLWwczCA/edit#slide=id.p) 

![p4-style-fail](https://user-images.githubusercontent.com/539017/88303844-c8781700-cd07-11ea-8fa9-01bc51ba5ac8.png)

#New Content

Might as well update the page with slightly reworded content (below):

## Greenpeace Planet 4 Styleguide

Planet 4 ❤️ open design. If you would like to help design Planet 4 then here’s how to get started:

[Read our onboarding doc!](https://docs.google.com/presentation/d/1WQGrLp7KcY2Vg5A6_jFv1pCipAMUmlXBKiAeLWwczCA/edit#slide=id.p)
[See the Design contribution page](https://planet4.greenpeace.org/create/contribute/#design)

### Contribute

This is currently used on all subprojects (eg. [master-theme](https://github.com/greenpeace/planet4-master-theme), [plugin-blocks](https://github.com/greenpeace/planet4-plugin-blocks)).

The source code for this lives in the [planet4-styleguide](https://github.com/greenpeace/planet4-styleguide) repository.

cc @lithrel

**Comment by oekeur** [comment] 2021-01-05 09:26
Seems like duplicate of #21

**Comment by andradaradu** [comment] 2021-09-02 16:03
@magalifatome can we close this?

**Comment by magalifatome** [comment] 2021-09-07 07:01
> @magalifatome can we close this?

Yep totally @andradaradu

**Closed** 2021-09-07 15:32 UTC
Labels: Documentation, Design, Bug, Change Log
